calc/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index, name='index'),
    path('home/', views.home2,name='home2'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/',views.results, name='results'),
    path('<int:question_id>/results/vote/', views.vote, name='vote')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('calc.urls')),
    path('admin/', admin.site.urls),
]

calc/models.py
from django.db import models
from django.utils import timezone
import datetime


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return (self.choice_text)

calc/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from .models import Question
from django.template import loader


# Create your views here.
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('calc/index.html')
    context = {'latest_question_list': latest_question_list}
    output = ', '.join(q.question_text for q in latest_question_list)

    return HttpResponse(template.render(context, request))
    # return render(request,'home.html')


def home2(request):
    return render(request, 'home.html')


def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not")
    return render(request, 'calc/detail.html', {'question': question})


def results(request, question_id):
    response = "You're looking at result of question {}."
    return HttpResponse(response.format(question_id))


def vote(request, question_id):
    return HttpResponse("You're voting on question {}".format(question_id))

calc/templates/calc/detail.html
<h1>{{ question }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

calc/templates/calc/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/calc/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

calc/templates/calc/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>